#include "Settings.h"
#include "AtomicFile.h"
#include "imgui.h"
#include <fstream>
#include <iostream>
#include <filesystem>
#include <sstream>
#include <vector>

Settings* Settings::instance = nullptr;

Settings::Settings() {
    ResetToDefaults();
}

Settings::~Settings() {
}

Settings& Settings::Instance() {
    if (!instance) {
        instance = new Settings();
        instance->LoadSettings();
    }
    return *instance;
}

void Settings::ResetToDefaults() {
    enableNotifications = true;
    enableAutoBackup = false;
    securityLevel = 2;  // High security by default
    backupRetentionDays = 30;
    enableLogging = true;
    theme = "Dark";
    themeChanged = false;
}

std::string Settings::GetSettingsFilePath() const {
    // Try multiple possible locations for the config directory
    std::vector<std::string> possiblePaths = {
        "./config/settings.conf",        // Current directory
        "../config/settings.conf",       // Parent directory (for build subdirectory)
        "../../config/settings.conf",    // Grandparent directory (for nested build dirs)
        "./config/settings.conf"         // Fallback to current directory
    };
    
    // Check if any existing config file exists
    for (size_t i = 0; i < possiblePaths.size() - 1; ++i) {
        if (std::filesystem::exists(possiblePaths[i])) {
            return possiblePaths[i];
        }
    }
    
    // If no existing file found, use the last path and create the directory
    std::string configDir = std::filesystem::path(possiblePaths.back()).parent_path();
    if (!std::filesystem::exists(configDir)) {
        std::filesystem::create_directories(configDir);
    }
    
    return possiblePaths.back();
}

bool Settings::LoadSettings() {
    std::string filePath = GetSettingsFilePath();
    
    if (!std::filesystem::exists(filePath)) {
        std::cout << "Settings file not found, using defaults" << std::endl;
        return SaveSettings(); // Create default settings file
    }
    
    // Reset to defaults first to ensure clean state
    ResetToDefaults();
    
    std::ifstream file(filePath);
    if (!file.is_open()) {
        std::cout << "Could not open settings file: " << filePath << std::endl;
        return false;
    }
    
    std::string line;
    while (std::getline(file, line)) {
        if (!ParseSettingsLine(line)) {
            std::cout << "Warning: Could not parse settings line: " << line << std::endl;
        }
    }
    
    file.close();
    std::cout << "Settings loaded successfully from: " << filePath << std::endl;
    return true;
}

bool Settings::ParseSettingsLine(const std::string& line) {
    // Skip empty lines and comments
    if (line.empty() || line[0] == '#') {
        return true;
    }
    
    size_t equalPos = line.find('=');
    if (equalPos == std::string::npos) {
        return false;
    }
    
    std::string key = line.substr(0, equalPos);
    std::string value = line.substr(equalPos + 1);
    
    // Trim whitespace
    key.erase(0, key.find_first_not_of(" \t"));
    key.erase(key.find_last_not_of(" \t") + 1);
    value.erase(0, value.find_first_not_of(" \t"));
    value.erase(value.find_last_not_of(" \t") + 1);
    
    // Parse different setting types
    if (key == "enableNotifications") {
        enableNotifications = (value == "true" || value == "1");
    } else if (key == "enableAutoBackup") {
        enableAutoBackup = (value == "true" || value == "1");
    } else if (key == "securityLevel") {
        try {
            securityLevel = std::stoi(value);
            if (securityLevel < 1 || securityLevel > 3) {
                securityLevel = 2; // Default to High
            }
        } catch (const std::exception&) {
            securityLevel = 2;
        }
    } else if (key == "backupRetentionDays") {
        try {
            backupRetentionDays = std::stoi(value);
            if (backupRetentionDays < 1) {
                backupRetentionDays = 30;
            }
        } catch (const std::exception&) {
            backupRetentionDays = 30;
        }
    } else if (key == "enableLogging") {
        enableLogging = (value == "true" || value == "1");
    } else if (key == "theme") {
        if (value == "Dark" || value == "Light" || value == "Auto") {
            theme = value;
        } else {
            theme = "Dark";
        }
    } else {
        return false; // Unknown key
    }
    
    return true;
}

bool Settings::SaveSettings() {
    std::string filePath = GetSettingsFilePath();

    std::ostringstream contents;
    contents << "# PQC Wallet Settings Configuration\n";
    contents << "# This file is automatically generated\n";
    contents << "# Boolean values: true/false or 1/0\n\n";
    contents << "enableNotifications=" << (enableNotifications ? "true" : "false") << "\n";
    contents << "enableAutoBackup=" << (enableAutoBackup ? "true" : "false") << "\n";
    contents << "securityLevel=" << securityLevel << "\n";
    contents << "backupRetentionDays=" << backupRetentionDays << "\n";
    contents << "enableLogging=" << (enableLogging ? "true" : "false") << "\n";
    contents << "theme=" << theme << "\n";

    if (!AtomicFile::Write(filePath, contents.str())) {
        std::cout << "Could not atomically save settings file: " << filePath << std::endl;
        return false;
    }
    
    std::cout << "Settings saved successfully to: " << filePath << std::endl;
    return true;
}

void Settings::ApplyTheme() const {
    if (theme == "Light") {
        ImGui::StyleColorsLight();
    } else if (theme == "Dark") {
        ImGui::StyleColorsDark();
    } else if (theme == "Auto") {
        // For Auto, we'll default to Dark for now
        // In a real implementation, you might check system theme
        ImGui::StyleColorsDark();
    } else {
        // Default fallback
        ImGui::StyleColorsDark();
    }
    
    // Shared layout tokens used by every window.
    const GuiMetrics& metrics = Metrics();
    ImGuiStyle& style = ImGui::GetStyle();
    style.WindowPadding = ImVec2(metrics.windowPadding, metrics.windowPadding);
    style.FramePadding = ImVec2(metrics.framePaddingX, metrics.framePaddingY);
    style.ItemSpacing = ImVec2(metrics.itemSpacing, metrics.itemSpacing);
    style.ItemInnerSpacing = ImVec2(metrics.itemInnerSpacing, 6.0f);
    style.CellPadding = ImVec2(metrics.itemSpacing, metrics.framePaddingY);
    style.WindowRounding = metrics.windowRounding;
    style.ChildRounding = metrics.childRounding;
    style.PopupRounding = metrics.popupRounding;
    style.FrameRounding = metrics.frameRounding;
    style.ScrollbarRounding = metrics.frameRounding;
    style.GrabRounding = metrics.frameRounding;
    style.TabRounding = metrics.frameRounding;
    style.ScrollbarSize = 12.0f;
    style.GrabMinSize = 10.0f;
    style.WindowBorderSize = 1.0f;
    style.ChildBorderSize = 1.0f;
    style.PopupBorderSize = 1.0f;
    style.FrameBorderSize = 0.0f;
    
    // Theme-specific customizations for better contrast
    ImVec4* colors = style.Colors;
    
    if (theme == "Light") {
        // Light theme customizations with better contrast
        colors[ImGuiCol_WindowBg] = ImVec4(0.965f, 0.973f, 0.984f, 1.0f);
        colors[ImGuiCol_ChildBg] = ImVec4(1.0f, 1.0f, 1.0f, 1.0f);
        colors[ImGuiCol_PopupBg] = ImVec4(1.0f, 1.0f, 1.0f, 0.99f);
        colors[ImGuiCol_MenuBarBg] = ImVec4(0.925f, 0.945f, 0.965f, 1.0f);
        colors[ImGuiCol_TitleBg] = ImVec4(0.925f, 0.945f, 0.965f, 1.0f);
        colors[ImGuiCol_TitleBgActive] = ImVec4(0.89f, 0.925f, 0.95f, 1.0f);
        colors[ImGuiCol_Header] = ImVec4(0.05f, 0.46f, 0.43f, 0.18f);
        colors[ImGuiCol_HeaderHovered] = ImVec4(0.05f, 0.46f, 0.43f, 0.28f);
        colors[ImGuiCol_HeaderActive] = ImVec4(0.05f, 0.46f, 0.43f, 0.38f);
        
        // Improve text contrast for light theme - ALL TEXT SHOULD BE DARK
        colors[ImGuiCol_Text] = ImVec4(0.0f, 0.0f, 0.0f, 1.0f);  // Black text for all controls
        colors[ImGuiCol_TextDisabled] = ImVec4(0.5f, 0.5f, 0.5f, 1.0f);  // Gray disabled text
        colors[ImGuiCol_TextSelectedBg] = ImVec4(0.3f, 0.6f, 1.0f, 0.35f);  // Selection background
        
        // Child window backgrounds (for sections)
        colors[ImGuiCol_Button] = ImVec4(0.89f, 0.91f, 0.94f, 1.0f);
        colors[ImGuiCol_ButtonHovered] = ImVec4(0.84f, 0.87f, 0.91f, 1.0f);
        colors[ImGuiCol_ButtonActive] = ImVec4(0.78f, 0.82f, 0.87f, 1.0f);
        
        // Border colors
        colors[ImGuiCol_Border] = ImVec4(0.80f, 0.84f, 0.89f, 1.0f);
        colors[ImGuiCol_BorderShadow] = ImVec4(0.0f, 0.0f, 0.0f, 0.0f);
        colors[ImGuiCol_Separator] = colors[ImGuiCol_Border];
        colors[ImGuiCol_SeparatorHovered] = ImVec4(0.05f, 0.46f, 0.43f, 0.65f);
        colors[ImGuiCol_SeparatorActive] = ImVec4(0.05f, 0.46f, 0.43f, 1.0f);
        colors[ImGuiCol_ScrollbarBg] = ImVec4(0.925f, 0.94f, 0.96f, 0.7f);
        colors[ImGuiCol_ScrollbarGrab] = ImVec4(0.72f, 0.77f, 0.83f, 1.0f);
        colors[ImGuiCol_ScrollbarGrabHovered] = ImVec4(0.62f, 0.69f, 0.77f, 1.0f);
        colors[ImGuiCol_ScrollbarGrabActive] = ImVec4(0.05f, 0.46f, 0.43f, 0.8f);
        colors[ImGuiCol_TableRowBg] = ImVec4(1.0f, 1.0f, 1.0f, 0.0f);
        colors[ImGuiCol_TableRowBgAlt] = ImVec4(0.90f, 0.93f, 0.96f, 0.45f);
        
        // Frame backgrounds (input fields, etc.)
        colors[ImGuiCol_FrameBg] = ImVec4(0.925f, 0.94f, 0.96f, 1.0f);
        colors[ImGuiCol_FrameBgHovered] = ImVec4(0.89f, 0.92f, 0.95f, 1.0f);
        colors[ImGuiCol_FrameBgActive] = ImVec4(0.86f, 0.90f, 0.94f, 1.0f);
        
        // Checkbox and radio button colors
        colors[ImGuiCol_CheckMark] = ImVec4(0.05f, 0.46f, 0.43f, 1.0f);
        
        // Slider colors
        colors[ImGuiCol_SliderGrab] = ImVec4(0.05f, 0.46f, 0.43f, 0.85f);
        colors[ImGuiCol_SliderGrabActive] = ImVec4(0.04f, 0.37f, 0.35f, 1.0f);
        
        // Tab colors
        colors[ImGuiCol_Tab] = ImVec4(0.89f, 0.91f, 0.94f, 1.0f);
        colors[ImGuiCol_TabHovered] = ImVec4(0.05f, 0.46f, 0.43f, 0.25f);
        colors[ImGuiCol_TabActive] = ImVec4(0.05f, 0.46f, 0.43f, 0.18f);
        colors[ImGuiCol_TabUnfocused] = ImVec4(0.8f, 0.8f, 0.8f, 1.0f);
        colors[ImGuiCol_TabUnfocusedActive] = ImVec4(0.85f, 0.85f, 0.85f, 1.0f);
        
    } else {
        // Dark theme customizations
        colors[ImGuiCol_WindowBg] = ImVec4(0.043f, 0.063f, 0.102f, 1.0f);
        colors[ImGuiCol_ChildBg] = ImVec4(0.059f, 0.086f, 0.137f, 1.0f);
        colors[ImGuiCol_PopupBg] = ImVec4(0.055f, 0.078f, 0.125f, 0.99f);
        colors[ImGuiCol_MenuBarBg] = ImVec4(0.055f, 0.078f, 0.125f, 1.0f);
        colors[ImGuiCol_TitleBg] = ImVec4(0.043f, 0.063f, 0.102f, 1.0f);
        colors[ImGuiCol_TitleBgActive] = ImVec4(0.07f, 0.10f, 0.16f, 1.0f);
        colors[ImGuiCol_Header] = ImVec4(0.08f, 0.72f, 0.65f, 0.16f);
        colors[ImGuiCol_HeaderHovered] = ImVec4(0.08f, 0.72f, 0.65f, 0.25f);
        colors[ImGuiCol_HeaderActive] = ImVec4(0.08f, 0.72f, 0.65f, 0.34f);
        
        // Ensure good text contrast for dark theme - ALL TEXT SHOULD BE LIGHT
        colors[ImGuiCol_Text] = ImVec4(1.0f, 1.0f, 1.0f, 1.0f);  // White text for all controls
        colors[ImGuiCol_TextDisabled] = ImVec4(0.6f, 0.6f, 0.6f, 1.0f);  // Light gray disabled text
        colors[ImGuiCol_TextSelectedBg] = ImVec4(0.3f, 0.6f, 1.0f, 0.35f);  // Selection background
        
        // Child window backgrounds (for sections)
        colors[ImGuiCol_Button] = ImVec4(0.10f, 0.14f, 0.22f, 1.0f);
        colors[ImGuiCol_ButtonHovered] = ImVec4(0.14f, 0.19f, 0.29f, 1.0f);
        colors[ImGuiCol_ButtonActive] = ImVec4(0.17f, 0.23f, 0.34f, 1.0f);
        
        // Border colors    
        colors[ImGuiCol_Border] = ImVec4(0.16f, 0.22f, 0.32f, 1.0f);
        colors[ImGuiCol_BorderShadow] = ImVec4(0.0f, 0.0f, 0.0f, 0.0f);
        colors[ImGuiCol_Separator] = colors[ImGuiCol_Border];
        colors[ImGuiCol_SeparatorHovered] = ImVec4(0.08f, 0.72f, 0.65f, 0.65f);
        colors[ImGuiCol_SeparatorActive] = ImVec4(0.08f, 0.72f, 0.65f, 1.0f);
        colors[ImGuiCol_ScrollbarBg] = ImVec4(0.043f, 0.063f, 0.102f, 0.7f);
        colors[ImGuiCol_ScrollbarGrab] = ImVec4(0.16f, 0.22f, 0.32f, 1.0f);
        colors[ImGuiCol_ScrollbarGrabHovered] = ImVec4(0.22f, 0.30f, 0.42f, 1.0f);
        colors[ImGuiCol_ScrollbarGrabActive] = ImVec4(0.08f, 0.72f, 0.65f, 0.8f);
        colors[ImGuiCol_TableRowBg] = ImVec4(0.059f, 0.086f, 0.137f, 0.0f);
        colors[ImGuiCol_TableRowBgAlt] = ImVec4(0.10f, 0.14f, 0.22f, 0.55f);
        
        // Frame backgrounds (input fields, etc.)
        colors[ImGuiCol_FrameBg] = ImVec4(0.075f, 0.11f, 0.18f, 1.0f);
        colors[ImGuiCol_FrameBgHovered] = ImVec4(0.10f, 0.15f, 0.23f, 1.0f);
        colors[ImGuiCol_FrameBgActive] = ImVec4(0.13f, 0.19f, 0.28f, 1.0f);
        
        // Checkbox and radio button colors
        colors[ImGuiCol_CheckMark] = ImVec4(0.18f, 0.83f, 0.75f, 1.0f);
        
        // Slider colors
        colors[ImGuiCol_SliderGrab] = ImVec4(0.08f, 0.72f, 0.65f, 0.85f);
        colors[ImGuiCol_SliderGrabActive] = ImVec4(0.18f, 0.83f, 0.75f, 1.0f);
        
        // Tab colors
        colors[ImGuiCol_Tab] = ImVec4(0.10f, 0.14f, 0.22f, 1.0f);
        colors[ImGuiCol_TabHovered] = ImVec4(0.08f, 0.72f, 0.65f, 0.25f);
        colors[ImGuiCol_TabActive] = ImVec4(0.08f, 0.72f, 0.65f, 0.18f);
        colors[ImGuiCol_TabUnfocused] = ImVec4(0.15f, 0.15f, 0.15f, 1.0f);
        colors[ImGuiCol_TabUnfocusedActive] = ImVec4(0.2f, 0.2f, 0.2f, 1.0f);
    }
    
    // Note: For button text to always be black, we will need to use 
    // ImGui::PushStyleColor/PopStyleColor in the UI code for each button
    // since ImGui doesn't have separate button text colors
}

void Settings::NotifyThemeChanged() const {
    // Set flag for main loop to detect theme change
    themeChanged = true;
    
    // Force immediate theme application
    ApplyTheme();
    
    // Additional actions could be added here to notify specific UI components
    // For now, ApplyTheme() should be sufficient since ImGui recalculates 
    // colors on the next frame
    std::cout << "Theme change notification sent - UI will update on next frame" << std::endl;
}

Settings::ThemeColors Settings::GetThemeColors() const {
    ThemeColors colors;
    
    if (theme == "Light") {
        // Light theme colors - darker colors for better contrast on light background
        // Primary text: Dark gray/black
        colors.primaryText[0] = 0.1f; colors.primaryText[1] = 0.1f; colors.primaryText[2] = 0.1f; colors.primaryText[3] = 1.0f;
        
        // Secondary text: Medium gray
        colors.secondaryText[0] = 0.4f; colors.secondaryText[1] = 0.4f; colors.secondaryText[2] = 0.4f; colors.secondaryText[3] = 1.0f;
        
        // Accent text: Dark blue
        colors.accentText[0] = 0.2f; colors.accentText[1] = 0.4f; colors.accentText[2] = 0.8f; colors.accentText[3] = 1.0f;
        
        // Success text: Dark green
        colors.successText[0] = 0.1f; colors.successText[1] = 0.6f; colors.successText[2] = 0.1f; colors.successText[3] = 1.0f;
        
        // Warning text: Dark orange/amber
        colors.warningText[0] = 0.8f; colors.warningText[1] = 0.5f; colors.warningText[2] = 0.0f; colors.warningText[3] = 1.0f;
        
        // Error text: Dark red
        colors.errorText[0] = 0.8f; colors.errorText[1] = 0.1f; colors.errorText[2] = 0.1f; colors.errorText[3] = 1.0f;
        
        // Info text: Dark cyan/teal
        colors.infoText[0] = 0.1f; colors.infoText[1] = 0.6f; colors.infoText[2] = 0.7f; colors.infoText[3] = 1.0f;

        colors.surface[0] = 1.0f; colors.surface[1] = 1.0f;
        colors.surface[2] = 1.0f; colors.surface[3] = 1.0f;
        colors.surfaceElevated[0] = 0.925f; colors.surfaceElevated[1] = 0.945f;
        colors.surfaceElevated[2] = 0.965f; colors.surfaceElevated[3] = 1.0f;
        colors.border[0] = 0.80f; colors.border[1] = 0.84f;
        colors.border[2] = 0.89f; colors.border[3] = 1.0f;
        
    } else {
        // Dark theme colors - brighter colors for contrast on dark background
        // Primary text: Light gray/white
        colors.primaryText[0] = 0.9f; colors.primaryText[1] = 0.9f; colors.primaryText[2] = 0.9f; colors.primaryText[3] = 1.0f;
        
        // Secondary text: Medium gray
        colors.secondaryText[0] = 0.7f; colors.secondaryText[1] = 0.7f; colors.secondaryText[2] = 0.7f; colors.secondaryText[3] = 1.0f;
        
        // Accent text: Light blue
        colors.accentText[0] = 0.7f; colors.accentText[1] = 0.9f; colors.accentText[2] = 1.0f; colors.accentText[3] = 1.0f;
        
        // Success text: Light green
        colors.successText[0] = 0.5f; colors.successText[1] = 0.8f; colors.successText[2] = 0.5f; colors.successText[3] = 1.0f;
        
        // Warning text: Light yellow
        colors.warningText[0] = 0.8f; colors.warningText[1] = 0.8f; colors.warningText[2] = 0.5f; colors.warningText[3] = 1.0f;
        
        // Error text: Light red
        colors.errorText[0] = 1.0f; colors.errorText[1] = 0.4f; colors.errorText[2] = 0.4f; colors.errorText[3] = 1.0f;
        
        // Info text: Light cyan
        colors.infoText[0] = 0.6f; colors.infoText[1] = 0.8f; colors.infoText[2] = 0.9f; colors.infoText[3] = 1.0f;

        colors.surface[0] = 0.059f; colors.surface[1] = 0.086f;
        colors.surface[2] = 0.137f; colors.surface[3] = 1.0f;
        colors.surfaceElevated[0] = 0.075f; colors.surfaceElevated[1] = 0.11f;
        colors.surfaceElevated[2] = 0.18f; colors.surfaceElevated[3] = 1.0f;
        colors.border[0] = 0.16f; colors.border[1] = 0.22f;
        colors.border[2] = 0.32f; colors.border[3] = 1.0f;
    }
    
    return colors;
}

const Settings::GuiMetrics& Settings::Metrics() {
    static const GuiMetrics metrics{};
    return metrics;
}

bool Settings::Button(const char* label, ButtonVariant variant,
                      float width, float height) const {
    const bool light = theme == "Light";
    ImVec4 background;
    ImVec4 hovered;
    ImVec4 active;
    ImVec4 textColor;

    switch (variant) {
        case ButtonVariant::Primary:
            background = light ? ImVec4(0.047f, 0.463f, 0.431f, 1.0f)
                               : ImVec4(0.055f, 0.647f, 0.58f, 1.0f);
            hovered = light ? ImVec4(0.055f, 0.647f, 0.58f, 1.0f)
                            : ImVec4(0.176f, 0.831f, 0.749f, 1.0f);
            active = ImVec4(0.04f, 0.37f, 0.345f, 1.0f);
            textColor = ImVec4(1.0f, 1.0f, 1.0f, 1.0f);
            break;
        case ButtonVariant::Danger:
            background = light ? ImVec4(0.86f, 0.15f, 0.15f, 1.0f)
                               : ImVec4(0.75f, 0.12f, 0.16f, 1.0f);
            hovered = ImVec4(0.94f, 0.27f, 0.27f, 1.0f);
            active = ImVec4(0.64f, 0.08f, 0.12f, 1.0f);
            textColor = ImVec4(1.0f, 1.0f, 1.0f, 1.0f);
            break;
        case ButtonVariant::Ghost:
            background = ImVec4(0.0f, 0.0f, 0.0f, 0.0f);
            hovered = light ? ImVec4(0.84f, 0.87f, 0.91f, 0.8f)
                            : ImVec4(0.14f, 0.19f, 0.29f, 0.8f);
            active = light ? ImVec4(0.78f, 0.82f, 0.87f, 1.0f)
                           : ImVec4(0.17f, 0.23f, 0.34f, 1.0f);
            textColor = light ? ImVec4(0.12f, 0.16f, 0.22f, 1.0f)
                              : ImVec4(0.90f, 0.93f, 0.97f, 1.0f);
            break;
        case ButtonVariant::Secondary:
        default:
            background = light ? ImVec4(0.89f, 0.91f, 0.94f, 1.0f)
                               : ImVec4(0.10f, 0.14f, 0.22f, 1.0f);
            hovered = light ? ImVec4(0.84f, 0.87f, 0.91f, 1.0f)
                            : ImVec4(0.14f, 0.19f, 0.29f, 1.0f);
            active = light ? ImVec4(0.78f, 0.82f, 0.87f, 1.0f)
                           : ImVec4(0.17f, 0.23f, 0.34f, 1.0f);
            textColor = light ? ImVec4(0.12f, 0.16f, 0.22f, 1.0f)
                              : ImVec4(0.90f, 0.93f, 0.97f, 1.0f);
            break;
    }

    ImGui::PushStyleColor(ImGuiCol_Button, background);
    ImGui::PushStyleColor(ImGuiCol_ButtonHovered, hovered);
    ImGui::PushStyleColor(ImGuiCol_ButtonActive, active);
    ImGui::PushStyleColor(ImGuiCol_Text, textColor);
    const float resolvedHeight = height > 0.0f ? height : Metrics().buttonHeight;
    const bool pressed = ImGui::Button(label, ImVec2(width, resolvedHeight));
    ImGui::PopStyleColor(4);
    return pressed;
}

bool Settings::IconButton(const char* label, UiIcon icon, ButtonVariant variant,
                          float width, float height) const {
    const float iconSize = 16.0f;
    const float gap = Metrics().itemInnerSpacing;
    const ImVec2 textSize = ImGui::CalcTextSize(label);
    const float resolvedWidth = width > 0.0f
        ? width
        : textSize.x + iconSize + gap + Metrics().framePaddingX * 2.0f;
    const float resolvedHeight = height > 0.0f ? height : Metrics().buttonHeight;
    const std::string hiddenLabel = std::string("##iconButton_") + label;
    const bool pressed = Button(hiddenLabel.c_str(), variant,
                                resolvedWidth, resolvedHeight);

    const ImVec2 minimum = ImGui::GetItemRectMin();
    const ImVec2 maximum = ImGui::GetItemRectMax();
    const float contentWidth = iconSize + gap + textSize.x;
    const float contentX = minimum.x +
        ((maximum.x - minimum.x) - contentWidth) * 0.5f;
    const float iconY = minimum.y + ((maximum.y - minimum.y) - iconSize) * 0.5f;
    const float textY = minimum.y + ((maximum.y - minimum.y) - textSize.y) * 0.5f;

    const bool strong = variant == ButtonVariant::Primary ||
                        variant == ButtonVariant::Danger;
    const auto colors = GetThemeColors();
    ImVec4 contentColor = strong
        ? ImVec4(1.0f, 1.0f, 1.0f, 1.0f)
        : ImVec4(colors.primaryText[0], colors.primaryText[1],
                 colors.primaryText[2], colors.primaryText[3]);
    contentColor.w *= ImGui::GetStyle().Alpha;
    DrawIconAt(icon, contentColor, ImVec2(contentX, iconY), iconSize);
    ImGui::GetWindowDrawList()->AddText(
        ImVec2(contentX + iconSize + gap, textY),
        ImGui::GetColorU32(contentColor), label);
    return pressed;
}

void Settings::DrawIcon(UiIcon icon, const ImVec4& color, float size,
                        bool advanceLayout) const {
    DrawIconAt(icon, color, ImGui::GetCursorScreenPos(), size);
    if (advanceLayout) {
        ImGui::Dummy(ImVec2(size, size));
    }
}

void Settings::DrawIconAt(UiIcon icon, const ImVec4& color,
                          const ImVec2& origin, float size) const {
    const ImVec2 center(origin.x + size * 0.5f, origin.y + size * 0.5f);
    const float scale = size / 20.0f;
    const float thickness = std::max(1.5f, 1.8f * scale);
    ImDrawList* drawList = ImGui::GetWindowDrawList();
    const ImU32 packedColor = ImGui::GetColorU32(color);

    switch (icon) {
        case UiIcon::Success:
            drawList->AddCircle(center, 8.0f * scale, packedColor, 24, thickness);
            drawList->AddLine(ImVec2(origin.x + 5.0f * scale, origin.y + 10.5f * scale),
                              ImVec2(origin.x + 8.5f * scale, origin.y + 14.0f * scale),
                              packedColor, thickness);
            drawList->AddLine(ImVec2(origin.x + 8.5f * scale, origin.y + 14.0f * scale),
                              ImVec2(origin.x + 15.5f * scale, origin.y + 6.5f * scale),
                              packedColor, thickness);
            break;
        case UiIcon::Warning: {
            const ImVec2 points[] = {
                ImVec2(center.x, origin.y + 2.0f * scale),
                ImVec2(origin.x + 18.0f * scale, origin.y + 17.0f * scale),
                ImVec2(origin.x + 2.0f * scale, origin.y + 17.0f * scale)
            };
            drawList->AddPolyline(points, 3, packedColor, thickness,
                                  ImDrawFlags_Closed);
            drawList->AddLine(ImVec2(center.x, origin.y + 7.0f * scale),
                              ImVec2(center.x, origin.y + 12.0f * scale),
                              packedColor, thickness);
            drawList->AddCircleFilled(ImVec2(center.x, origin.y + 14.7f * scale),
                                      1.0f * scale, packedColor);
            break;
        }
        case UiIcon::Error:
            drawList->AddCircle(center, 8.0f * scale, packedColor, 24, thickness);
            drawList->AddLine(ImVec2(origin.x + 6.5f * scale, origin.y + 6.5f * scale),
                              ImVec2(origin.x + 13.5f * scale, origin.y + 13.5f * scale),
                              packedColor, thickness);
            drawList->AddLine(ImVec2(origin.x + 13.5f * scale, origin.y + 6.5f * scale),
                              ImVec2(origin.x + 6.5f * scale, origin.y + 13.5f * scale),
                              packedColor, thickness);
            break;
        case UiIcon::Archive:
            drawList->AddRect(ImVec2(origin.x + 2.0f * scale, origin.y + 4.0f * scale),
                              ImVec2(origin.x + 18.0f * scale, origin.y + 18.0f * scale),
                              packedColor, 2.0f * scale, 0, thickness);
            drawList->AddLine(ImVec2(origin.x + 2.0f * scale, origin.y + 8.0f * scale),
                              ImVec2(origin.x + 18.0f * scale, origin.y + 8.0f * scale),
                              packedColor, thickness);
            drawList->AddLine(ImVec2(origin.x + 8.0f * scale, origin.y + 12.0f * scale),
                              ImVec2(origin.x + 12.0f * scale, origin.y + 12.0f * scale),
                              packedColor, thickness);
            break;
        case UiIcon::File:
            drawList->AddRect(ImVec2(origin.x + 4.0f * scale, origin.y + 2.0f * scale),
                              ImVec2(origin.x + 16.0f * scale, origin.y + 18.0f * scale),
                              packedColor, 1.5f * scale, 0, thickness);
            drawList->AddLine(ImVec2(origin.x + 11.0f * scale, origin.y + 2.0f * scale),
                              ImVec2(origin.x + 16.0f * scale, origin.y + 7.0f * scale),
                              packedColor, thickness);
            drawList->AddLine(ImVec2(origin.x + 11.0f * scale, origin.y + 2.0f * scale),
                              ImVec2(origin.x + 11.0f * scale, origin.y + 7.0f * scale),
                              packedColor, thickness);
            break;
        case UiIcon::Folder:
            drawList->AddRect(ImVec2(origin.x + 2.0f * scale, origin.y + 6.0f * scale),
                              ImVec2(origin.x + 18.0f * scale, origin.y + 17.0f * scale),
                              packedColor, 2.0f * scale, 0, thickness);
            drawList->AddLine(ImVec2(origin.x + 3.0f * scale, origin.y + 6.0f * scale),
                              ImVec2(origin.x + 8.0f * scale, origin.y + 6.0f * scale),
                              packedColor, thickness);
            drawList->AddLine(ImVec2(origin.x + 4.0f * scale, origin.y + 3.0f * scale),
                              ImVec2(origin.x + 8.0f * scale, origin.y + 3.0f * scale),
                              packedColor, thickness);
            drawList->AddLine(ImVec2(origin.x + 8.0f * scale, origin.y + 3.0f * scale),
                              ImVec2(origin.x + 10.0f * scale, origin.y + 6.0f * scale),
                              packedColor, thickness);
            break;
        case UiIcon::Lock:
            drawList->AddRect(ImVec2(origin.x + 4.0f * scale, origin.y + 9.0f * scale),
                              ImVec2(origin.x + 16.0f * scale, origin.y + 18.0f * scale),
                              packedColor, 2.0f * scale, 0, thickness);
            drawList->PathArcTo(ImVec2(center.x, origin.y + 9.0f * scale),
                                5.0f * scale, 3.14159f, 6.28318f, 16);
            drawList->PathStroke(packedColor, thickness);
            break;
        case UiIcon::Info:
        default:
            drawList->AddCircle(center, 8.0f * scale, packedColor, 24, thickness);
            drawList->AddCircleFilled(ImVec2(center.x, origin.y + 6.0f * scale),
                                      1.1f * scale, packedColor);
            drawList->AddLine(ImVec2(center.x, origin.y + 9.0f * scale),
                              ImVec2(center.x, origin.y + 15.0f * scale),
                              packedColor, thickness);
            break;
    }

}

void Settings::DialogHeader(UiIcon icon, const char* title, const char* subtitle) const {
    const auto colors = GetThemeColors();
    ImVec4 iconColor(colors.accentText[0], colors.accentText[1],
                     colors.accentText[2], colors.accentText[3]);
    if (icon == UiIcon::Success) {
        iconColor = ImVec4(colors.successText[0], colors.successText[1],
                           colors.successText[2], colors.successText[3]);
    } else if (icon == UiIcon::Warning) {
        iconColor = ImVec4(colors.warningText[0], colors.warningText[1],
                           colors.warningText[2], colors.warningText[3]);
    } else if (icon == UiIcon::Error) {
        iconColor = ImVec4(colors.errorText[0], colors.errorText[1],
                           colors.errorText[2], colors.errorText[3]);
    }

    DrawIcon(icon, iconColor, 24.0f);
    ImGui::SameLine(0.0f, Metrics().itemSpacing);
    ImGui::BeginGroup();
    ImGui::TextUnformatted(title);
    if (subtitle != nullptr && subtitle[0] != '\0') {
        ImGui::TextDisabled("%s", subtitle);
    }
    ImGui::EndGroup();
    ImGui::Spacing();
    ImGui::Separator();
    ImGui::Spacing();
}

void Settings::PushBlackButtonText() {
    const bool light = Instance().GetTheme() == "Light";
    ImGui::PushStyleColor(ImGuiCol_Text,
                          light ? ImVec4(0.12f, 0.16f, 0.22f, 1.0f)
                                : ImVec4(0.90f, 0.93f, 0.97f, 1.0f));
}

void Settings::PopBlackButtonText() {
    // Pop the black text color
    ImGui::PopStyleColor(1);
}
